### ISSUE TITLE
Dependence error

### ISSUE THREAD

**Issue by ABuffEr** [KenBonny/KenBonny.CheckHibp#1]
Hi,
I run the win10 version from console, but receive this error:
Error:
  An assembly specified in the application dependencies manifest (KenBonny.CheckHibp.deps.json) was not found:
    package: 'RestSharp', version: '106.3.0-alpha0018'
    path: 'lib/netstandard2.0/RestSharp.dll'
Can you help? Thanks :)

**Comment by KenBonny** [comment]
Wow... you found this. That in itself is impressive. I'm going to have to disappoint you, I can't help you.

This was an experiment from +2 years ago iirc. I used this to call the HIBP api at the time. This was before rate limiting and before he implemented a paywall. You're literally looking at a weekend experiment I forgot about.

Sorry that I can't help you further with this. Is there something specific you are trying to accomplish? Maybe I can lend a hand with that. 😃

**Comment by ABuffEr** [comment]
Hi KenBonny,
first, thanks for your reply! But no worry, simply I have subscribed on HIBP some time ago, and recently I started to use aliases, I asked myself whether HIBP supports them, and landed on your blog.
So, well... thanks for the experiment, I greatly appreciated its existence 😀

**Comment by KenBonny** [comment]
I'm using [1Password](https://1password.com/) (on Troy's recommendation) to store my passwords. It has a [Watchtower](https://watchtower.1password.com/) feature that integrates with HIBP. Hope this helps. That's how I check compromised passwords on accounts where I use aliases.
